### ISSUE TITLE
Transactions - ‘Transaction  Page’

### ISSUE THREAD

**Issue by Buckno1** [MyBitFoundation/MyBit-Go#140]
Whenever ‘Amount’ or ‘Status’ triangle up or down clicked on page, when ‘Date’ button clicked after, does not auto populate to most recent transactions appears out of sync, the ‘Date’ & ‘Amount’ tab.  The only way I can reset transaction history to latest transaction is to click out of transactions and click back in.

**Comment by jjperezaguinaga** [comment]
This was closed as it should had been solved already, @Buckno1 please let us know if that isn't the case.

**Comment by Buckno1** [comment]
This is now solved
